on:
  workflow_dispatch:
  push:

env:
  RUN: |
    whiskers zed.tera --overrides '{"accent": ["mauve"]}'

jobs:
  whiskers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm themes/*.json
      # Cache Rust toolchain and dependencies
      - name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
            ~/.cargo
            target/
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
      - run: cargo install catppuccin-whiskers@=2.5.1

      - name: Get Latest Release Asset
        run: |
          curl -s https://api.github.com/repos/catppuccin/zed/releases/latest \
          | grep "browser_download_url.*catppuccin.*mauve.*json" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -qi - -P themes/

      - name: Test Against Latest Release
        run: |
          ${{ env.RUN }} --check > whiskers_output.txt 2>&1 || true
          echo "### Whiskers Diff Output" >> $GITHUB_STEP_SUMMARY
          cat whiskers_output.txt >> $GITHUB_STEP_SUMMARY

      - run: ${{ env.RUN }}
      - name: Verify JSON
        run: cat themes/catppuccin-mauve.json | jq -n > /dev/null
