on:
  workflow_dispatch:
  push:

env:
  RUN: 'whiskers zed.tera --overrides ''{"accent": ["mauve"]}'''

jobs:
  whiskers:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Verify Checked-In JSON
        run: cat themes/catppuccin-mauve.json | jq
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install catppuccin-whiskers@=2.5.1
      - name: Verify Generated JSON
        run: ${{ env.RUN }}
      - run: cat themes/catppuccin-mauve.json | jq

      # diffs against latest release
      - run: rm -f themes/*.json
      - name: Get Latest Release Asset
        run: |
          curl -s https://api.github.com/repos/catppuccin/zed/releases/latest \
          | grep "browser_download_url.*catppuccin.*mauve.*json" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -qi - -P themes/
      - name: Check Against Latest Release
        run: |
          ${{ env.RUN }} --check > whiskers_output.txt 2>&1 || true
          echo "### Whiskers Diff Output" >> $GITHUB_STEP_SUMMARY
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
          cat whiskers_output.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "</details>" >> $GITHUB_STEP_SUMMARY
